go14_compiler:
  - go1.4-bootstrap
cgo:
  - false
  - true  # [not osx]
cgo_int:
  - 0
  - 1     # [not osx]
nocgo:
  - true
  - false # [not osx]
cgo_var:
  - nocgo
  - cgo
conda_goarch:
  - amd64
conda_goos:
  - linux
  - darwin
  - windows
conda_goplatform:
  - linux-64
  - osx-64
  - win-64
conda_gofile:
  - ELF
  - Mach-O
  - PE32+
zip_keys:
  - 
    - cgo
    - nocgo
    - cgo_var
    - cgo_int
  - 
    - conda_goplatform
    - conda_goos
    - conda_gofile
