# ########################################################################### #
# NOTE: If you change this file, you must regenerate the feedstock.           #
#   - conda smithy regenerate                                                 #
#   - @conda-forge-admin, please rerender                                     #
# ########################################################################### #

# Select the MACOSX Deployment target
# This will change depending on the version of go
# For the correct deployment target, please see go's Release notes
# c.f.: https://golang.org/doc/go1.16#darwin
macos_min_version:         # [osx]
  - '10.12'                # [osx]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - '10.12'                # [osx]
CONDA_BUILD_SYSROOT:       # [osx]
  - /opt/MacOSX10.12.sdk   # [osx]


# Static build downloaded for use as our bootstrap compiler
go_bootstrap_ver: 1.11.13


# Select the GO variants that we are building
# The variant names, and versions come from https://bit.ly/conda-go-select
go_variant_str:
  - cgo
  - nocgo
go_variant_ver:
  - 2.3.0
  - 2.2.0

# One-hot-encoding of the variant selection above
cgo:
  - true
  - false

#
# Tie the variables together
zip_keys:
  -
    - go_variant_str
    - go_variant_ver
    - cgo
  -                             # [linux and x86_64]
    - c_compiler_version        # [linux and x86_64]
    - cxx_compiler_version      # [linux and x86_64]
    - fortran_compiler_version  # [linux and x86_64]


# Build using updated toolchains that use a CentOS 7-based sysroot; this
# section can be removed once the top-level cbc.yaml for defaults has been
# transitioned over to these newer toolchains.
c_compiler_version:         # [linux and x86_64]
  - 8.4                     # [linux and x86_64]
  - 9.3                     # [linux and x86_64]

cxx_compiler_version:       # [linux and x86_64]
  - 8.4                     # [linux and x86_64]
  - 9.3                     # [linux and x86_64]

fortran_compiler_version:   # [linux and x86_64]
  - 8.4                     # [linux and x86_64]
  - 9.3                     # [linux and x86_64]
