# ########################################################################### #
# NOTE: If you change this file, you must renerate the conda-forge feedstock. #
#   - conda smithy regenerate                                                 #
#   - @conda-forge-admin, please rerender                                     #
# ########################################################################### #

# Select the MACOSX Deployment target
# This will change depending on the version of go
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - '10.10'                # [osx]


# We use go1.4 as our bootstrap compiler
go14_compiler:
  - go1.4-bootstrap


# Select the GO variants that we are building
# The variant names, and versions come from https://bit.ly/conda-go-select
go_variant_str:
  - nocgo
  - cgo
go_variant_ver:
  - 1.3.1
  - 1.2.1

# One-hot-encoding of the variant selection above
cgo:
  - False
  - True
nocgo:
  - True
  - False

#
# Tie the variables together
zip_keys:
  -
    - go_variant_str
    - go_variant_ver
    - cgo
    - nocgo
