conda_goarch:
  - ppc64le
  - amd64
  - 386
  - amd64
  - amd64
  - 386
conda_goos:
  - linux
  - linux
  - linux
  - darwin
  - windows
  - windows
conda_goplatform:
  - linux-ppc64le
  - linux-64
  - linux-32
  - osx-64
  - win-64
  - win-32
conda_gofile:
  - ELF
  - ELF
  - ELF
  - Mach-O
  - PE32+
  - PE32
zip_keys:
  -
    - conda_goplatform
    - conda_goos
    - conda_goarch
    - conda_gofile
