{% set name = "go" %}
{% set version = "1.17.13" %}

package:
  name: {{ name }}-{{ go_variant_str }}
  version: {{ version }}

source:
  - folder: go
    url: https://dl.google.com/{{ name }}/go{{ version }}.src.tar.gz
    sha256: a1a48b23afb206f95e7bbaa9b898d965f90826f6f1d1fc0c1d784ada0cd300fd
    patches:
      # Please see patches/README.md for more details
      - patches/0001-issue10607-is-only-valid-when-running-with-CGO.patch
      - patches/0002-Fix-cgo_fortran-test-setup-for-conda.patch
      - patches/0003-Add-CC-C-CPP-LD-FLAGS-to-script_test-extraEnvKeys.patch
      - patches/0004-Inherit-CGO_-environment-variables.patch
      - patches/0005-Add-conda-aware-default-values-for-GOPATH-and-GOBIN.patch
      - patches/0006-cmd-link-internal-ld-disable-testWindowsBuildmodeCSh.patch

  # Update this with a release from https://go.dev/dl/
  - folder: go-bootstrap  # [aarch64 or ppc64le or osx or win64 or (linux and x86_64)]
    url: https://go.dev/dl/go{{ version }}.linux-arm64.tar.gz  # [aarch64]
    sha256: 49960821948b9c6b14041430890eccee58c76b52e2dbaafce971c3c38d43df9f  # [aarch64]

    url: https://go.dev/dl/go{{ version }}.linux-amd64.tar.gz  # [linux and x86_64]
    sha256: acc512fbab4f716a8f97a8b3fbaa9ddd39606a28be6c2515ef7c6c6311acffde  # [linux and x86_64]

    url: https://go.dev/dl/go{{ version }}.linux-ppc64le.tar.gz  # [ppc64le]
    sha256: 4137984aa353de9c5ec1bd8fb3cd00a0624b75eafa3d4ec13d2f3f48261dba2e  # [ppc64le]

    url: https://go.dev/dl/go{{ version }}.windows-amd64.zip  # [win64]
    sha256: b33584c1d93b0e9c783de876b7aa99d3018bdeccd396aeb6d516a74e9d88d55f  # [win64]

    url: https://go.dev/dl/go{{ version }}.darwin-arm64.tar.gz  # [osx and arm64]
    sha256: e4ccc9c082d91eaa0b866078b591fc97d24b91495f12deb3dd2d8eda4e55a6ea  # [osx and arm64]

    url: https://go.dev/dl/go{{ version }}.darwin-amd64.tar.gz  # [osx and x86_64]
    sha256: c101beaa232e0f448fab692dc036cd6b4677091ff89c4889cc8754b1b29c6608  # [osx and x86_64]

build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  force_ignore_keys:   # [win]
    - c_compiler        # [win]
    - cxx_compiler      # [win]
    - fortran_compiler  # [win]
  # test data links to these DSOs
  missing_dso_whitelist:
    - $RPATH/libc.so.6             # [linux and not cgo]
    - /usr/lib/libSystem.B.dylib   # [osx]
    - $SYSROOT\System32\winmm.dll  # [win]
  number: 0
  skip: True  # [not osx]
  # trigger: 1

requirements:
  run:
    - {{ pin_subpackage(name, exact=true) }}
    - {{ compiler('c') }}  # [unix and cgo]
    - {{ compiler('m2w64_c') }}  # [win and cgo]

test:
  commands:
    - go help

outputs:
  - name: {{ name }}
    script: {{ go_variant_str }}/build.sh   # [unix]
    script: {{ go_variant_str }}/build.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}        # [unix and cgo]
        - {{ compiler('cxx') }}      # [unix and cgo]
      #  - {{ compiler('fortran') }}  # [unix and cgo]

        - {{ compiler('m2w64_c') }}        # [win and cgo]
        - {{ compiler('m2w64_cxx') }}      # [win and cgo]
      #  - {{ compiler('m2w64_fortran') }}  # [win and cgo]
      run:
        - _go_select =={{ go_variant_ver }}={{ go_variant_str }}
      run_constrained:
        # TODO: Move to run section once conda/conda#9845 is fixed
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET }}  # [osx]

        - {{ pin_compatible(compiler('c')) }}        # [unix and cgo]
        - {{ pin_compatible(compiler('cxx')) }}      # [unix and cgo]
      #  - {{ pin_compatible(compiler('fortran')) }}  # [unix and cgo]

        - {{ pin_compatible(compiler('m2w64_c')) }}        # [win and cgo]
        - {{ pin_compatible(compiler('m2w64_cxx')) }}      # [win and cgo]
      #  - {{ pin_compatible(compiler('m2w64_fortran')) }}  # [win and cgo]
    test:
      requires:
        - {{ compiler('c') }}        # [unix and cgo]
        - binutils                   # [linux and cgp]
        - {{ compiler('m2w64_c') }}  # [win and cgo]
        - git  # [linux]
        - perl
      files:
        - {{ go_variant_str }}
      commands:
        - chmod +x {{ go_variant_str }}/test.sh   # [unix]
        - ./{{ go_variant_str }}/test.sh   # [unix]
        - {{ go_variant_str }}/test.bat  # [win]
    about:
      home: https://go.dev/
      license: BSD-3-Clause
      license_family: BSD
      license_file: go/LICENSE
      summary: The Go Programming Language

about:
  home: https://go.dev/
  license: BSD-3-Clause
  license_family: BSD
  license_file: go/LICENSE
  summary: The Go Programming Language ({{ go_variant_str }})
  description: |
    Go is expressive, concise, clean, and efficient. Its concurrency mechanisms
    make it easy to write programs that get the most out of multicore and
    networked machines, while its novel type system enables flexible and
    modular program construction. Go compiles quickly to machine code yet has
    the convenience of garbage collection and the power of run-time reflection.
    It's a fast, statically typed, compiled language that feels like a
    dynamically typed, interpreted language.
  doc_url: https://go.dev/doc
  dev_url: https://github.com/golang/

extra:
  feedstock-name: go
  recipe-maintainers:
    - nehaljwani
    - scopatz
    - sodre
    - stuarteberg
    - xhochy
