travis:
  secure:
    BINSTAR_TOKEN: sM+9Rp+kiaL8T9CEYH4xYLlpZ3Ygs/qrrnDj3A6Oxw5n91nUEsnBnhc+M6wA1VXbuZ6oVish0UJ9BFmTLP7wwjC7juoI9IWsedZNUsZqPGGnFsDMaGNdHRCXawXa1Igoeuq/GqKk6GzK53NRU11FWnavb8PYG9/r6Dyy+8Pj0e3g9pmxyvsE4amisH3ZdmHL8HfMXsPaff2fWp8tEVjrX+rxzue93/kKy+nmqG4/2Q9Rm786Ef39DCWYRbOp7y4OwU/wuXu+1Ss7viESL1KO77FRgs1XueVN5dhPXVb0c0ZRZTQB6iTuMBr8NeRGN8HW6M9ApaGZLpCKtwPTMP6PttfGG7bMbKpk8kMDxykp/6k1b81KuFcUh5Gd2wFlJ1gND1658J1ziNDNyoTfcT3c67You6Q4XSlSrFMvtpl6g/bi/vV5AmIyOPDAhXOzVnirEvkrymRfuNKczbmWD+vGHWNIau8OML6CukdtqLXf3izQGAryXhTMC5v7UxCU4IV8E1z+W8zrC9BmdSUvRSrJ7n2lN/kQvqQuShPmHUu7pks+Tt3tHChI26KXXQgl4uPmhk+6tzZgn4EAqQio8avGKdKvQWbgzsQJ/9iOQ7m3/aStPIaHXLbONpXAvJhaG8vUOn9zByvKPOOEwfO311SIq9/POrTisnpUyJ2MxzUjhbg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
